### ISSUE TITLE
Enable touch-sensitive keyboard scrolling on Passport

### ISSUE THREAD

**Issue by GoogleCodeExporter** [canadainc/oct-10#131]
```
ListView:
scrollRole: ScrollRole.Main
```

Original issue reported on code.google.com by `canadai...@gmail.com` on 15 Jan 2015 at 9:53

**Comment by canadainc** [comment]
e3f7a60926b80f5457c54f2a802c323462398527

**Comment by canadainc** [comment]
Verified on Classic 10.3.2.2801 with GCR 4.5.0.0, and R135 10.3.1.2744
