### ISSUE TITLE
French localization

### ISSUE THREAD

**Issue by GoogleCodeExporter** [canadainc/oct-10#53]
```
App needs to be localized to support French (Canada).
```

Original issue reported on code.google.com by `canadai...@gmail.com` on 13 Jan 2014 at 7:17

**Comment by canadainc** [comment]
b50dea239113edbfe99fcfee3febdccc1b6e2211

**Comment by canadainc** [comment]
0e3804b3cd22bd2c23bd0fb412116c63976e8947
