### ISSUE TITLE
Implement the calendar_exceptions table

### ISSUE THREAD

**Issue by GoogleCodeExporter** [canadainc/oct-10#79]
```
Make sure we don't show schedules for excluded dates.
```

Original issue reported on code.google.com by `canadai...@gmail.com` on 6 Apr 2014 at 6:06

**Comment by canadainc** [comment]
fc9e79aff261193a439241b8ccd40fdb15c177d0

**Comment by canadainc** [comment]
Verified on Classic 10.3.2.2801 with GCR 4.5.0.0, and R135 10.3.1.2744
